name: Controllo modifiche ultimo merge

on:
  workflow_dispatch:  # permette il trigger manuale da GitHub UI

jobs:
  check-merged-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # necessario per accedere alla cronologia dei merge

      - name: Trova ultimo merge commit
        run: |
          last_merge=$(git log --merges -n 1 --pretty=format:"%H")
          echo "Ultimo merge commit: $last_merge"
          echo "last_merge_commit=$last_merge" >> $GITHUB_ENV

      - name: Lista file modificati nell'ultimo merge
        run: |
          echo "File modificati:"
          git show --name-only ${{ env.last_merge_commit }}

      - name: Loop sui file modificati
        run: |
          echo "Analisi file modificati:"
          for file in $(git diff-tree --no-commit-id --name-only -r ${{ env.last_merge_commit }}); do
            echo "➤ $file"
            # qui puoi aggiungere logica su file specifici, ad esempio:
            # if [[ $file == src/* ]]; then echo "File nel codice sorgente modificato!"; fi
          done
