name: Post welcome comment and show PR changes

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  welcome:
    name: Post welcome comment
    runs-on: ubuntu-latest
    steps:
      - run: gh pr comment "$PR_URL" --body "Benvenuto nella Pull Request! 🎉"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}

  check-merged-changes:
    name: Check PR changed files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Post number of changed files
        run: |
          gh pr comment "$PR_URL" --body "${{ github.event.pull_request.changed_files }} files changed in this PR. Please review them carefully."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}

      - name: Comment with list of modified files
        run: |
          FILES=$(gh pr view "$PR_URL" --json files --jq '.files[].path')
          echo "📦 File modificati nella PR:"
          echo "$FILES"
          gh pr comment "$PR_URL" --body "📄 File modificati:<br> \`\`\`$FILES\`\`\` <br>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}

      - name: Mostra dettagli delle modifiche per ogni file
        run: |
              echo "📄 Analisi dettagliata dei file modificati:"

              BASE_SHA=${{ github.event.pull_request.base.sha }}
              HEAD_SHA=${{ github.event.pull_request.head.sha }}

              for file in $(git diff --name-only "$BASE_SHA" "$HEAD_SHA"); do
                echo "➤ File modificato: $file"

                DIFF=$(git diff --unified=3 "$BASE_SHA" "$HEAD_SHA" -- "$file" | sed '/^diff /d;/^index /d;/^--- /d;/^\+\+\+ /d')

                COMMENT=$'📄 File modificato: '"$file"$'<br>'
                COMMENT+=$'--------------------------------------------<br>'
                COMMENT+=$'\`\`\`$DIFF\`\`\`'
                COMMENT+=$'<br>--------------------------------------------<br>'

                gh pr comment "$PR_URL" --body "$COMMENT"
              done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
